version: '3'
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - h2database

  h2database:
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521"
    environment:
      H2_OPTIONS: -tcp -tcpAllowOthers
