version: '3.8'
services:
  springboot-app:
    build: .
    image: mohamedelhamzi203/idsdetection:${TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2database:1521/mem:testdb
    depends_on:
      h2database:
        condition: service_healthy
    networks:
      - app-network

  h2database:
    image: oscarfonts/h2  # Use this verified H2 image
    ports:
      - "1521:1521"  # H2 TCP port
      - "8082:81"    # H2 web console port (81 internally)
    environment:
      H2_OPTIONS: -tcp -tcpAllowOthers -web -webAllowOthers
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
