version: '3'
services:
  springboot-app:
    build: .
    image: mohamedelhamzi203/idsdetection:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2database:1521/mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - h2database
    networks:
      - idsnet
    entrypoint: ["/wait-for-it.sh", "h2database:1521", "--", "java", "-jar", "/app/app.jar"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  h2database:
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521"
    environment:
      H2_OPTIONS: -tcp -tcpAllowOthers -web -webAllowOthers
    networks:
      - idsnet
  zap:
    image: zaproxy/zap-stable:latest
    depends_on:
      - springboot-app
    networks:
      - idsnet
    volume:
      - ./:/zap/wrk

networks:       
  idsnet:
    name: idsnet
    driver: bridge
