version: '3'
services:
  springboot-app:
    build: .
    image: mohamedelhamzi203/idsdetection:${TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2database:1521/mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - h2database
    entrypoint: ["/wait-for-it.sh", "h2database:1521", "--", "java", "-jar", "/app/app.jar"]

  h2database:
     command: 
      - "-web" 
      - "-webAllowOthers" 
      - "-tcp" 
      - "-tcpAllowOthers" 
      - "-webPort" 
      - "8082"  # Port for H2 web console
    ports:
      - "1521:1521"  # TCP port for database connections
      - "8082:8082"  # Web console port
    networks:
      - app-network
