name: Docker Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build the Spring Boot app with Maven
      run: mvn clean install -DskipTests -f ./webtest/webtest/pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and start containers
      run: |
        docker-compose -f ./webtest/webtest/docker-compose.yaml up --build -d

    - name: Wait for application startup
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8080/actuator/health; then
            echo "Application is up!"
            exit 0
          fi
          sleep 5
        done
        echo "Application failed to start"
        exit 1

    - name: Verify app is running
      run: |
        curl --fail -v http://localhost:8080/actuator/health

    - name: Debug container logs if failed
      if: ${{ failure() }}
      run: |
        docker-compose -f ./webtest/webtest/docker-compose.yaml logs springboot-app

    - name: Push Docker images to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker-compose -f ./webtest/webtest/docker-compose.yaml push
