name: Docker Spring Boot CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install -DskipTests -f ./webtest/webtest/pom.xml

    - name: Set up Docker tools
      uses: docker/setup-compose-action@v3

    - name: Build and start containers
      run: |
        docker-compose -f ./webtest/webtest/docker-compose.yaml up --build -d

    - name: Wait for application startup
      run: |
        for i in {1..15}; do
          if curl -sSf http://localhost:8080/actuator/health >/dev/null; then
            echo "Application is up!"
            exit 0
          fi
          sleep 10
          echo "Attempt $i/15 - Retrying..."
        done
        echo "Application failed to start"
        docker-compose -f ./webtest/webtest/docker-compose.yaml logs springboot-app
        exit 1

    - name: Verify app is running
      run: curl --fail -v http://localhost:8080/actuator/health

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker-compose -f ./webtest/webtest/docker-compose.yaml push
