name: Docker Spring Boot CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Specify JDK distribution
        
    - name: List directory contents
      run: ls -R

    - name: Build the Spring Boot app with Maven
      run: mvn clean install -DskipTests -f ./webtest/webtest/pom.xml

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Build Docker images with Docker Compose
      run: docker-compose -f ./webtest/webtest/docker-compose.yaml build

    - name: Run Docker Compose up
      run: |
        docker-compose -f ./webtest/webtest/docker-compose.yaml up -d
    - name: see docker log
      run: |
        docker-compose -f ./webtest/webtest/docker-compose.yaml logs springboot-app
        docker-compose -f ./webtest/webtest/docker-compose.yaml ps
    - name: Push Docker images to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        # Login with credentials
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        # Push images
        docker-compose -f ./webtest/webtest/docker-compose.yaml push
